FROM python:3.11-slim

WORKDIR /app

COPY requirements.api.txt .
RUN pip install --no-cache-dir -r requirements.api.txt

COPY . .
ENV PYTHONPATH=/app/src
EXPOSE 8000

CMD ["uvicorn", "mlops_forecasting.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
