apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forecasting-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "10"
spec:
  rules:
    - host: forecasting.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: forecasting-api
                port:
                  number: 80
